### PR TITLE
Added support for pancam and hazcams

### PR DESCRIPTION
**Pull request by jumpjack**
- 0.3.0 by Jumpjack
- Added support for pancam, rear hazcam and front hazcam for MER1/MER2
- Added support for alternate texture (EFF or FFL)
- Added comments/explanations on naming convention

### CODE REVIEW

**Comment by phaseIV** [comment]
Hey jumpjack, nice to see you want to enhance the functionality of the addon. I really appreciate your work on that.
Unfortunately I'm leaving for a holiday break and will be without computer for quite some time so I cannot check your pulls right away. So please be patient, I will review the additions when possible. 
One thing comes to mind, since the scope of this addon is to (re)generate 3d environments from mission data, I wonder if Hazcams and Pancams images can provide 3d data to create meshes?

**Comment by jumpjack** [comment]
Just some.. thousands :-)

image

https://pds-imaging.jpl.nasa.gov/search/?fq=ATLAS_MISSION_NAME%3A%22mars%20exploration%20rover%22&fq=-ATLAS_THUMBNAIL_URL%3Abrwsnotavail.jpg&fq=PRODUCT_TYPE%3Axyz&q=*%3A*

I discovered it while studying old .PFB files from nasa archives: they were created using SGI OpenGL Performer from Silicon Graphics, now disappeared from internet. Each .PFB groups multiple 3d files into one single mesh, and each .PFB files contains the list of all textures; by texture you can easily obtaining XYZ product id.

I just finished updating my PFB-converter: now it lists all textures contained into a PFB file, in a format which can be directly pasted into blender to have all meshes and textures imported:
https://github.com/jumpjack/VST-converter/blob/main/PFB-converter-kaitai-040.html


Last version of my modded Blender script now ignores all missing textures and meshes, so it can continue processing input list without stopping:

https://github.com/jumpjack/Blender-Navcam-Importer/blob/master/import_marsrovernavcam_v2.py

Problem is that last digit of product id is the product version: mesh product can have multiple versions, hence ending in 2, 3, 4,.... but texture products have only one version, so sometimes the script fails in finding them; but if you download the into cache and run script again, it will load them from cache.

You can find PFB files here:
https://pds-imaging.jpl.nasa.gov/data/mer/spirit/mer2mw_0xxx/data/navcam/site0137/

Have a good holiday!

**Comment by jumpjack** [comment]
Did you have the chance to take a look?
I also tried to implement color texture, but it's too complex for me: I know where the data are, but I don't know where to put them in Blender.

**Comment by phaseIV** [comment]
Sorry this took so long, jumpjack. I couldn't run it myself but from the documents you provided it fits exactly in the scope of this addon. So thanks!

And regarding the recent issues you posted, can you send me an email at info@marslife.org?

**Pull request merged**
